openapi: 3.0.1
info:
  title: INAD - Domicilio Digitale
  description: >-
    API rese disponibili da INAD al Catalogo delle API previsto nel modello di
    interoperabilità delle pubbliche amministrazioni.


    Pattern Model applicati:

    - CRUD_REST

    - [ID_AUTH_REST_02] Direct Trust con certificato X.509

    - [INTEGRITY_REST_01] Integrità del payload del messaggio REST

    - [NONBLOCK_PULL_REST] Not Blocking Pull REST
  contact:
    name: Infocamere S.C.p.A.
    url: https://www.infocamere.it/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  version: 1.0.0-SNAPSHOT
servers:
  - url: https://domiciliodigitaleapi.oscl.infocamere.it
    description: Generated server url
tags:
  - name: API ESTRAZIONI MULTIPLE
  - name: API ESTRAZIONI PUNTUALI
paths:
  /rest/inad/v1/domiciliodigitale/elenco:
    post:
      tags:
        - API ESTRAZIONI MULTIPLE
      summary: >-
        Consente di inserire una richiesta di estrazione di domicili digitali a
        partire dall'elenco di codici fiscali forniti (fino ad un massimo di
        1.000). Per ogni codice fiscale si ottiene il domicilio digitale
        corrispondente al momento dell'estrazione e, in caso di domicilio
        digitale eletto in qualità di Professionista, anche l'attività
        professionale esercitata. L'elaborazione della richiesta è asincrona:
        l'elenco, identificato da un codice univoco,  è reso disponibile
        mediante un servizio di recupero.
      operationId: richiestaElencoDomiciliDigitali
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RichiestaElencoDomiciliDigitali'
        required: true
      responses:
        '202':
          description: >-
            JSON di risposta attraverso il quale l'Erogatore fornisce, insieme
            all'acknowledgement della richiesta, l'URL per interrogare lo stato
            di processamento utilizzando l'<i>HTTP header Location</i>. L'elenco
            è individuato da un codice identificativo univoco.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaRichiestaElencoDomiciliDigitali'
        '400':
          description: BAD_REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        '401':
          description: UNAUTHORIZED
          content:
            application/json: {}
        '403':
          description: FORBIDDEN
          content:
            application/json: {}
        '404':
          description: NOT_FOUND
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        '500':
          description: INTERNAL_SERVER_ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        '503':
          description: SERVICE_UNAVAILABLE
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        default:
          description: RispostaRichiestaElencoDomiciliDigitali
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaRichiestaElencoDomiciliDigitali'
      security:
        - Authorization:
            - global
  /rest/inad/v1/domiciliodigitale/{cf}:
    get:
      tags:
        - API ESTRAZIONI PUNTUALI
      summary: >-
        Consente di ottenere il domicilio digitale corrispondente al codice
        fiscale al momento della consultazione e, in caso di domicilio digitale
        eletto in qualità di Professionista, anche l'attività professionale
        esercitata.
      operationId: recuperoDomicilioDigitale
      parameters:
        - name: cf
          in: path
          description: CF per cui si effettua la ricerca
          required: true
          schema:
            type: string
          example: '01234567890'
      responses:
        '200':
          description: >-
            JSON di risposta che restituisce il domicilio digitale estratto. Per
            un codice fiscale è possibile estrarre al massimo due domicili
            digitali eletti in qualità di persona fisica/Ente e/o
            Professionista. Per domicilio digitale eletto in qualità di
            Professionista è estratta anche l'attività professionale esercitata.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaRicercaDomicilioDigitale'
        '400':
          description: BAD_REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        '401':
          description: UNAUTHORIZED
          content:
            application/json: {}
        '403':
          description: FORBIDDEN
          content:
            application/json: {}
        '404':
          description: NOT_FOUND
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        '500':
          description: INTERNAL_SERVER_ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        '503':
          description: SERVICE_UNAVAILABLE
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        default:
          description: RispostaRicercaDomicilioDigitale
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaRicercaDomicilioDigitale'
      security:
        - Authorization:
            - global
  /rest/inad/v1/domiciliodigitale/verifica/{cf}:
    get:
      tags:
        - API ESTRAZIONI PUNTUALI
      summary: >-
        Fornito in input il domicilio digitale (indirizzo PEC), codice fiscale e
        data, il servizio consente di verificare se, alla data indicata, il
        domicilio digitale era associato al codice fiscale indicato.
      operationId: verificaDomicilioDigitale
      parameters:
        - name: cf
          in: path
          description: Codice fiscale del domicilio da ricercare
          required: true
          schema:
            type: string
          example: '01234567890'
        - name: domicilioDigitale
          in: query
          description: Indirizzo del domicilio da ricercare
          required: true
          schema:
            type: string
        - name: data
          in: query
          description: Data in formato ddMMyyyy
          required: true
          schema:
            type: string
          example: '03112021'
      responses:
        '200':
          description: >-
            JSON di risposta che restituisce l'esito della verifica: domicilio
            associato (<i>true</i>) o domicilio non associato (<i>false</i>).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaVerificaDomicilioDigitale'
        '400':
          description: BAD_REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        '401':
          description: UNAUTHORIZED
          content:
            application/json: {}
        '403':
          description: FORBIDDEN
          content:
            application/json: {}
        '404':
          description: NOT_FOUND
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        '500':
          description: INTERNAL_SERVER_ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        '503':
          description: SERVICE_UNAVAILABLE
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        default:
          description: RispostaVerificaDomicilioDigitale
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaVerificaDomicilioDigitale'
      security:
        - Authorization:
            - global
  /rest/inad/v1/domiciliodigitale/elenco/{id}/risultato:
    get:
      tags:
        - API ESTRAZIONI MULTIPLE
      summary: >-
        Consente di recuperare l'elenco dei domicili digitali individuato dal
        codice identificativo univoco.
      operationId: recuperoElencoDomiciliDigitali
      parameters:
        - name: id
          in: path
          description: Identificativo univoco della richiesta di elenco
          required: true
          schema:
            type: string
          example: f8c3de3d-1fea-4d7c-a8b0-29f63c4c3454
      responses:
        '200':
          description: >-
            Risposta di tipo JSON che rappresenta l'elenco dei domicili digitali
            estratti. Per un codice fiscale è possibile estrarre al massimo due
            domicili digitali eletti in qualità di persona fisica/Ente e/o
            Professionista. I codici fiscali per i quali non è presente il
            domicilio digitale sono comunque indicati nella risposta con
            informazione non valorizzata. L'elenco è reso disponibile per un
            massimo di 48 ore, trascorse le quali l'elenco viene cancellato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaElencoDomiciliDigitali'
        '400':
          description: BAD_REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        '401':
          description: UNAUTHORIZED
          content:
            application/json: {}
        '403':
          description: FORBIDDEN
          content:
            application/json: {}
        '404':
          description: NOT_FOUND
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        '500':
          description: INTERNAL_SERVER_ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        '503':
          description: SERVICE_UNAVAILABLE
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        default:
          description: RispostaElencoDomiciliDigitali
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaElencoDomiciliDigitali'
      security:
        - Authorization:
            - global
  /rest/inad/v1/domiciliodigitale/elenco/{id}:
    get:
      tags:
        - API ESTRAZIONI MULTIPLE
      summary: >-
        Consente di verificare lo stato del processamento della richiesta
        dell'elenco dei domicili digitali individuato dal codice identificativo
        univoco.
      operationId: verificaStatoRichiestaElencoDomiciliDigitali
      parameters:
        - name: id
          in: path
          description: Identificativo univoco della richiesta di elenco
          required: true
          schema:
            type: string
          example: f8c3de3d-1fea-4d7c-a8b0-29f63c4c3454
      responses:
        '200':
          description: >-
            JSON di risposta attraverso il quale l'Erogatore indica, sulla base
            dello stato del processamento, che l'operazione non è completata.
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/RispostaStatoRichiestaElencoDomiciliDigitali
        '303':
          description: >-
            JSON di risposta attraverso il quale l'Erogatore indica, sulla base
            dello stato del processamento, che l'elenco è pronto all'URL
            indicato nell'<i>HTTP header Location</i>.
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/RispostaStatoRichiestaElencoDomiciliDigitali
        '400':
          description: BAD_REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        '401':
          description: UNAUTHORIZED
          content:
            application/json: {}
        '403':
          description: FORBIDDEN
          content:
            application/json: {}
        '404':
          description: NOT_FOUND
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        '500':
          description: INTERNAL_SERVER_ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        '503':
          description: SERVICE_UNAVAILABLE
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        default:
          description: RispostaStatoRichiestaElencoDomiciliDigitali
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/RispostaStatoRichiestaElencoDomiciliDigitali
      security:
        - Authorization:
            - global
components:
  schemas:
    Errore:
      required:
        - status
        - type
      type: object
      properties:
        status:
          type: string
          description: Codice di errore
          example: <HTTP_CODE>
          enum:
            - '400'
            - '401'
            - '403'
            - '404'
            - '500'
            - '503'
        type:
          type: string
          description: Tipologia di errore
          example: <HTTP_STATUS>
          enum:
            - BAD_REQUEST
            - UNAUTHORIZED
            - FORBIDDEN
            - NOT_FOUND
            - INTERNAL_SERVER_ERROR
            - SERVICE_UNAVAILABLE
        detail:
          type: string
          description: Descrizione di dettaglio dello specifico problema verificatosi
          example: <detail_error>
    RispostaRichiestaElencoDomiciliDigitali:
      required:
        - dataOraRichiesta
        - id
        - messaggio
        - stato
      type: object
      properties:
        stato:
          type: string
          description: Stato della richiesta
          example: Accettato
        messaggio:
          type: string
          description: Messaggio di conferma dell'avvenuta presa in carico della richiesta
          example: Richiesta elenco presa in carico
        id:
          type: string
          description: Codice identificativo univoco della richiesta di estrazione
          example: f8c3de3d-1fea-4d7c-a8b0-29f63c4c3454
        dataOraRichiesta:
          type: string
          description: >-
            Data/Ora di inserimento della richiesta in formato <dd/MM/yyyy
            hh:mm:ss>
          example: 20/11/2021 17:32:12
    RichiestaElencoDomiciliDigitali:
      required:
        - codiciFiscali
        - riferimentoPratica
      type: object
      properties:
        codiciFiscali:
          type: array
          description: Array di codici fiscali in input
          example: '[<cf1>,<cf2>,<cf3>]'
          items:
            type: string
            description: Array di codici fiscali in input
            example: '[<cf1>,<cf2>,<cf3>]'
        riferimentoPratica:
          type: string
          description: >-
            Riferimento del procedimento amministrativo per il quale si richiede
            l'elenco
          example: <num_protocollo|num_fascicolo|num_verbale>
    InfoUtilizzo:
      required:
        - dataFineValidita
        - motivazione
      type: object
      properties:
        motivazione:
          type: string
          description: Motivazione cessazione
          example: <CESSAZIONE_UFFICIO|CESSAZIONE_VOLONTARIA>
        dataFineValidita:
          type: string
          description: Data/Ora fine validità in formato <dd/MM/yyyy hh:mm:ss>
          example: 20/11/2021 17:32:12
      description: Info utilizzo del singolo Domicilio Digitale
    RispostaRicercaDomicilioDigitale:
      required:
        - cf
        - dataEstrazione
        - domiciliDigitali
      type: object
      properties:
        cf:
          type: string
          description: Codice Fiscale di Input
          example: '01234567890'
        dataEstrazione:
          type: string
          description: Data/Ora estrazione in formato <dd/MM/yyyy hh:mm:ss>
          example: 20/11/2021 17:32:12
        domiciliDigitali:
          required:
            - domicilioDigitale
            - infoUtilizzo
          type: object
          properties:
            domicilioDigitale:
              pattern: '"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$"'
              type: string
              description: Indirizzo PEC Domicilio Digitale
              example: example@pec.it
            professioneEsercitata:
              type: string
              description: Professione esercitata. Non presente per Persona Fisica/Ente
              example: Avvocato
            infoUtilizzo:
              $ref: '#/components/schemas/InfoUtilizzo'
          description: Elenco Domicili Digitali afferenti al Codice Fiscale di Input
    RispostaVerificaDomicilioDigitale:
      required:
        - dataOraVerifica
        - esito
      type: object
      properties:
        esito:
          type: boolean
          description: Esito della verifica
          example: true
          enum:
            - true
            - false
        dataOraVerifica:
          type: string
          description: Data/Ora estrazione in formato <dd/MM/yyyy hh:mm:ss>
          example: 20/11/2021 17:32:12
    RispostaElencoDomiciliDigitali:
      required:
        - elenco
      type: object
      properties:
        elenco:
          required:
            - domicilioDigitale
            - infoUtilizzo
          type: object
          properties:
            domicilioDigitale:
              pattern: '"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$"'
              type: string
              description: Indirizzo PEC Domicilio Digitale
              example: example@pec.it
            professioneEsercitata:
              type: string
              description: Professione esercitata. Non presente per Persona Fisica/Ente
              example: Avvocato
            infoUtilizzo:
              $ref: '#/components/schemas/InfoUtilizzo'
          description: Elenco Domicili Digitali estratti
    RispostaStatoRichiestaElencoDomiciliDigitali:
      required:
        - messaggio
        - stato
      type: object
      properties:
        stato:
          type: string
          description: Stato della richiesta
          example: Processamento
        messaggio:
          type: string
          description: Messaggio descrittivo dello stato della richiesta
          example: Richiesta elenco in fase di processamento
        href:
          type: string
          description: >-
            Posizione alla quale è disponibile scaricare il risultato
            dell'elaborazione.
          example: >-
            https://<dominioOrganizzativo>/rest/inad/v1/domiciliodigitale/elenco/{id}/risultato
  securitySchemes:
  
    # non ricordo che sia stato previsto l'utilizzo di https://swagger.io/docs/specification/authentication/api-keys/
    Authorization:
      type: apiKey
      name: Authorization
      in: header
